federation_version: =2.4.3
subgraphs:
# Local .graphql file
  questionnaire:
    routing_url: http://localhost:4010/graphql
    schema:
      file: ./questionnaire.graphql
  userInput:
    routing_url: http://localhost:4020/graphql
    schema:
      file: ./userInput.graphql
# Subgraph introspection
  # questionnaire:
  #   routing_url: http://localhost:4010/graphql  # <- can be omitted if the same as introspection URL
  #   schema:
  #     subgraph_url: http://localhost:4010/graphql
      # introspection_headers:  # Optional headers to include in introspection request
      #   Authorization: Bearer ${env.PEOPLE_AUTH_TOKEN}

  # Apollo Studio graph ref
  # questionnaire:
  #   routing_url: http://localhost:4005  # <- can be omitted if matches existing URL in Studio
  #   schema:
  #     graphref: mygraph@current
  #     subgraph: actors