federation_version: =2.3.2
subgraphs:
# Local .graphql file
  # questionnaire:
  #   routing_url: http://localhost:4010/graphql
  #   schema:
  #     file: ../questionnaire/schema.graphql
# Subgraph introspection
  questionnaire:
    routing_url: http://localhost:4000/graphql  # <- can be omitted if the same as introspection URL
    schema:
      subgraph_url: http://localhost:4010/graphql
      # introspection_headers:  # Optional headers to include in introspection request
      #   Authorization: Bearer ${env.PEOPLE_AUTH_TOKEN}

  # Apollo Studio graph ref
  # questionnaire:
  #   routing_url: http://localhost:4005  # <- can be omitted if matches existing URL in Studio
  #   schema:
  #     graphref: mygraph@current
  #     subgraph: actors